import type { Metadata } from "next";
import "./globals.css";

import { cn } from "@/lib/utils";
import { fontBody, fontDisplay } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("", fontBody.variable, fontDisplay.variable)}>
        {children}
      </body>
    </html>
  );
}
